// <auto-generated />
using System;
using BTCPayServer.RockstarDev.Plugins.LnurlSource.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.RockstarDev.Plugins.LnurlSource.Data.Migrations
{
    [DbContext(typeof(LnurlSourceDbContext))]
    partial class LnurlSourceDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.RockstarDev.Plugins.LnurlSource")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.LnurlSource.Data.Models.LnurlSourceInvoice", b =>
                {
                    b.Property<string>("PaymentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<long>("AmountMilliSatoshi")
                        .HasColumnType("bigint");

                    b.Property<string>("Bolt11")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("InvoiceId")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("VerifyUrl")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.HasKey("PaymentHash");

                    b.HasIndex("InvoiceId");

                    b.ToTable("Invoices", "BTCPayServer.RockstarDev.Plugins.LnurlSource");
                });
#pragma warning restore 612, 618
        }
    }
}
