// <auto-generated />
using System;
using BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Migrations
{
    [DbContext(typeof(PluginDbContext))]
    [Migration("20260113040543_RenameToFeeBlockTarget")]
    partial class RenameToFeeBlockTarget
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.RockstarDev.Plugins.WalletSweeper")
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.SweepConfiguration", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AccountXpub")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("AddressGapLimit")
                        .HasColumnType("integer");

                    b.Property<bool>("AutoEnabled")
                        .HasColumnType("boolean");

                    b.Property<bool>("AutoGenerateLabel")
                        .HasColumnType("boolean");

                    b.Property<string>("ConfigName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("Created")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("CurrentBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("DerivationPath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Description")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<int>("DestinationType")
                        .HasColumnType("integer");

                    b.Property<string>("EncryptedPassword")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("EncryptedSeed")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<int>("FeeBlockTarget")
                        .HasColumnType("integer");

                    b.Property<int>("IntervalMinutes")
                        .HasColumnType("integer");

                    b.Property<DateTimeOffset?>("LastMonitored")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("LastSwept")
                        .HasColumnType("timestamp with time zone");

                    b.Property<decimal>("MaximumBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("MinimumBalance")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<decimal>("ReserveAmount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("StoreId")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<DateTimeOffset>("Updated")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StoreId");

                    b.HasIndex("StoreId", "ConfigName");

                    b.ToTable("SweepConfigurations", "BTCPayServer.RockstarDev.Plugins.WalletSweeper");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.SweepHistory", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("DestinationAddress")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<decimal>("Fee")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("SweepConfigurationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("SweepDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("TransactionId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("TriggerType")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<int>("UtxoCount")
                        .HasColumnType("integer");

                    b.Property<decimal?>("WeightedAverageCostBasis")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("SweepConfigurationId");

                    b.HasIndex("SweepDate");

                    b.ToTable("SweepHistories", "BTCPayServer.RockstarDev.Plugins.WalletSweeper");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.TrackedUtxo", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<decimal>("Amount")
                        .HasPrecision(18, 8)
                        .HasColumnType("decimal(18,8)");

                    b.Property<int>("Confirmations")
                        .HasColumnType("integer");

                    b.Property<string>("CostBasisSource")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<decimal?>("CostBasisUsd")
                        .HasPrecision(18, 2)
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DerivationPath")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<bool>("IsSpent")
                        .HasColumnType("boolean");

                    b.Property<string>("Outpoint")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<DateTimeOffset>("ReceivedDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("SpentDate")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("SpentInSweepTxId")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<string>("SweepConfigurationId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("TxId")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int>("Vout")
                        .HasColumnType("integer");

                    b.HasKey("Id");

                    b.HasIndex("IsSpent");

                    b.HasIndex("Outpoint")
                        .IsUnique();

                    b.HasIndex("SweepConfigurationId");

                    b.HasIndex("SweepConfigurationId", "IsSpent");

                    b.ToTable("TrackedUtxos", "BTCPayServer.RockstarDev.Plugins.WalletSweeper");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.SweepHistory", b =>
                {
                    b.HasOne("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.SweepConfiguration", "SweepConfiguration")
                        .WithMany()
                        .HasForeignKey("SweepConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SweepConfiguration");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.TrackedUtxo", b =>
                {
                    b.HasOne("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.SweepConfiguration", "SweepConfiguration")
                        .WithMany("TrackedUtxos")
                        .HasForeignKey("SweepConfigurationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("SweepConfiguration");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.WalletSweeper.Data.Models.SweepConfiguration", b =>
                {
                    b.Navigation("TrackedUtxos");
                });
#pragma warning restore 612, 618
        }
    }
}
