// <auto-generated />
using System;
using BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data.Migrations
{
    [DbContext(typeof(OfflinePaymentPluginDbContext))]
    partial class OfflinePaymentPluginDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("BTCPayServer.RockstarDev.Plugins.OfflinePayment")
                .HasAnnotation("ProductVersion", "10.0.6")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data.OfflineMethodConfig", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<string>("AccountAddress")
                        .HasColumnType("text");

                    b.Property<string>("AccountName")
                        .HasColumnType("text");

                    b.Property<string>("AccountNumber")
                        .HasColumnType("text");

                    b.Property<string>("BankAddress")
                        .HasColumnType("text");

                    b.Property<string>("BankName")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DisplayName")
                        .HasColumnType("text");

                    b.Property<string>("EstimatedSettlementTime")
                        .HasColumnType("text");

                    b.Property<string>("Instructions")
                        .HasColumnType("text");

                    b.Property<bool>("IsEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("MethodId")
                        .HasColumnType("text");

                    b.Property<string>("ReferenceTemplate")
                        .HasColumnType("text");

                    b.Property<string>("RoutingNumber")
                        .HasColumnType("text");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<string>("SupportContact")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("StoreId", "MethodId")
                        .IsUnique();

                    b.ToTable("OfflineMethodConfigs", "BTCPayServer.RockstarDev.Plugins.OfflinePayment");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data.OfflinePendingPayment", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("AdminConfirmedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTimeOffset?>("AdminInvalidatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("AdminUserId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset?>("CustomerMarkedSentAt")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("CustomerNote")
                        .HasColumnType("text");

                    b.Property<string>("InvoiceId")
                        .HasColumnType("text");

                    b.Property<string>("MethodConfigId")
                        .HasColumnType("text");

                    b.Property<string>("MethodId")
                        .HasColumnType("text");

                    b.Property<string>("RemittanceFileUrl")
                        .HasColumnType("text");

                    b.Property<string>("ResolvedReference")
                        .HasColumnType("text");

                    b.Property<int>("Status")
                        .HasColumnType("integer");

                    b.Property<string>("StoreId")
                        .HasColumnType("text");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("timestamp with time zone");

                    b.HasKey("Id");

                    b.HasIndex("MethodConfigId");

                    b.ToTable("OfflinePendingPayments", "BTCPayServer.RockstarDev.Plugins.OfflinePayment");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data.OfflinePendingPayment", b =>
                {
                    b.HasOne("BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data.OfflineMethodConfig", "MethodConfig")
                        .WithMany("PendingPayments")
                        .HasForeignKey("MethodConfigId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("MethodConfig");
                });

            modelBuilder.Entity("BTCPayServer.RockstarDev.Plugins.OfflinePayments.Data.OfflineMethodConfig", b =>
                {
                    b.Navigation("PendingPayments");
                });
#pragma warning restore 612, 618
        }
    }
}
