<Project Sdk="Microsoft.NET.Sdk">

    <PropertyGroup>
        <TargetFramework>net10.0</TargetFramework>
        <ImplicitUsings>enable</ImplicitUsings>
        <Nullable>enable</Nullable>
        <OutputType>Exe</OutputType>
        <IsPackable>false</IsPackable>
        <StaticWebAssetsEnabled>false</StaticWebAssetsEnabled>
    </PropertyGroup>

    <ItemGroup>
        <PackageReference Include="Microsoft.Playwright.NUnit" Version="1.48.0" />
    </ItemGroup>

    <ItemDefinitionGroup>
        <ProjectReference>
            <Properties>StaticWebAssetsEnabled=false</Properties>
        </ProjectReference>
    </ItemDefinitionGroup>

    <ItemGroup>
        <ProjectReference Include="..\submodules\btcpayserver\BTCPayServer\BTCPayServer.csproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
        <ProjectReference Include="..\submodules\btcpayserver\BTCPayServer.Tests\BTCPayServer.Tests.csproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
        <ProjectReference Include="..\Plugins\BTCPayServer.RockstarDev.Plugins.LnurlVerify\BTCPayServer.RockstarDev.Plugins.LnurlVerify.csproj" />
        <ProjectReference Include="..\Plugins\BTCPayServer.RockstarDev.Plugins.Payroll\BTCPayServer.RockstarDev.Plugins.Payroll.csproj">
            <PrivateAssets>all</PrivateAssets>
        </ProjectReference>
    </ItemGroup>

</Project>
